# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

# Setup
title: Operação Serenata de Amor
tagline: Inteligência artificial para controle social da administração pública
url: https://www.serenata.ai
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Operação Serenata de Amor
  url: https://serenata.ai
  email: contato@serenata.ai

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/datasciencebr/serenata-website

# i18n
plugins:
  - jekyll-multiple-languages-plugin
languages:
  - pt-br
  - en
exclude_from_localizations:
  - javascript
  - css
